name: Name of the Github Action
run-name: The run name (not sure what this is)
on: [push]
jobs:
  The-Name-Of-The-Job-Here:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This action will run on push event!"
      - run: php --version
      - run: echo "We just run php --version command to show php version"
      - run: echo "${{ github.actor }} ${{ runner.os }} ${{ github.event_name }} ${{ github.ref }} ${{ github.repository }} ${{ github.workspace }} ${{ job.status }}"
      - run: echo "We just echoed variables of github"
      - run: echo "End of Job"
