name: Name of the Github Action
run-name: The run name (not sure what this is)
on: [push]
jobs:
  The-Name-Of-The-Job-Here:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This action will run on push event!"
      - run: php --version
      - run: echo "We just run php --version command to show php version"
      - run: echo "${{ runner.os }} && ${{ github.actor }}"
      - run: echo "We just echoed runner.os and github.actor to test the && sign will work"
      - run: echo "${{ github.event_name }}"
      - run: echo "We just echoed github.event_name"
      - run: echo "${{ github.ref }}"
      - run: echo "We just echoed github.ref"
      - run: echo "${{ github.repository }}"
      - run: echo "We just echoed github.repository"
      - run: echo "${{ github.workspace }}"
      - run: echo "We just echoed github.workspace"
      - run: echo "${{ job.status }}"
      - run: echo "We just echoed job.status"
      - run: echo "End of Job"
